window.env = {
  "MANPATH": "/opt/local/share/man:/opt/homebrew/share/man:/usr/share/man:/usr/local/share/man:/opt/local/share/man:/opt/homebrew/share/man::",
  "TERM_PROGRAM": "vscode",
  "NODE": "/usr/local/bin/node",
  "INIT_CWD": "/Users/edgarramirez/Documents/TDR/frontend",
  "SHELL": "/bin/zsh",
  "TERM": "xterm-256color",
  "TMPDIR": "/var/folders/zy/6nx2s3md4h5fkfht168m4wn40000gn/T/",
  "HOMEBREW_REPOSITORY": "/opt/homebrew",
  "npm_config_metrics_registry": "https://registry.npmjs.org/",
  "npm_config_global_prefix": "/usr/local",
  "TERM_PROGRAM_VERSION": "1.89.1",
  "MallocNanoZone": "0",
  "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
  "ZDOTDIR": "/Users/edgarramirez",
  "COLOR": "1",
  "npm_config_noproxy": "",
  "npm_config_local_prefix": "/Users/edgarramirez/Documents/TDR/frontend",
  "USER": "edgarramirez",
  "COMMAND_MODE": "unix2003",
  "npm_config_globalconfig": "/usr/local/etc/npmrc",
  "SSH_AUTH_SOCK": "/private/tmp/com.apple.launchd.GjQfgLRlnO/Listeners",
  "__CF_USER_TEXT_ENCODING": "0x1F5:0:86",
  "npm_execpath": "/usr/local/lib/node_modules/npm/bin/npm-cli.js",
  "PATH": "/Users/edgarramirez/Documents/TDR/frontend/node_modules/.bin:/Users/edgarramirez/Documents/TDR/node_modules/.bin:/Users/edgarramirez/Documents/node_modules/.bin:/Users/edgarramirez/node_modules/.bin:/Users/node_modules/.bin:/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin:/Users/edgarramirez/Documents/TDR/frontend/node_modules/.bin:/Users/edgarramirez/Documents/TDR/node_modules/.bin:/Users/edgarramirez/Documents/node_modules/.bin:/Users/edgarramirez/node_modules/.bin:/Users/node_modules/.bin:/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin:/Users/edgarramirez/Downloads/google-cloud-sdk/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/edgarramirez/Downloads/google-cloud-sdk/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/opt/homebrew/bin:/opt/homebrew/sbin",
  "_": "/Users/edgarramirez/Documents/TDR/frontend/node_modules/.bin/react-dotenv",
  "npm_package_json": "/Users/edgarramirez/Documents/TDR/frontend/package.json",
  "__CFBundleIdentifier": "com.microsoft.VSCode",
  "USER_ZDOTDIR": "/Users/edgarramirez",
  "npm_config_init_module": "/Users/edgarramirez/.npm-init.js",
  "npm_config_userconfig": "/Users/edgarramirez/.npmrc",
  "PWD": "/Users/edgarramirez/Documents/TDR/frontend",
  "npm_command": "run-script",
  "EDITOR": "vi",
  "npm_lifecycle_event": "build",
  "LANG": "es_ES.UTF-8",
  "npm_package_name": "frontend",
  "XPC_FLAGS": "0x0",
  "VSCODE_GIT_ASKPASS_EXTRA_ARGS": "",
  "npm_config_node_gyp": "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js",
  "XPC_SERVICE_NAME": "0",
  "npm_package_version": "0.1.0",
  "VSCODE_INJECTION": "1",
  "HOME": "/Users/edgarramirez",
  "SHLVL": "3",
  "VSCODE_GIT_ASKPASS_MAIN": "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js",
  "HOMEBREW_PREFIX": "/opt/homebrew",
  "LOGNAME": "edgarramirez",
  "npm_config_cache": "/Users/edgarramirez/.npm",
  "npm_lifecycle_script": "react-dotenv && react-scripts build",
  "VSCODE_GIT_IPC_HANDLE": "/var/folders/zy/6nx2s3md4h5fkfht168m4wn40000gn/T/vscode-git-a14f03b00d.sock",
  "npm_config_user_agent": "npm/9.5.0 node/v18.14.2 darwin arm64 workspaces/false",
  "HOMEBREW_CELLAR": "/opt/homebrew/Cellar",
  "INFOPATH": "/opt/homebrew/share/info:/opt/homebrew/share/info:",
  "GIT_ASKPASS": "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh",
  "VSCODE_GIT_ASKPASS_NODE": "/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)",
  "COLORTERM": "truecolor",
  "npm_config_prefix": "/usr/local",
  "npm_node_execpath": "/usr/local/bin/node",
  "REACT_APP_API_URL": "http://localhost:8002"
};