# Generated by Django 4.2.13 on 2024-05-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casetas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
