# Generated by Django 4.2.13 on 2024-05-08 22:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('casetas', '0002_ruta_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='nombre_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='lugar_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lugar_destino_orden', to='casetas.lugar'),
        ),
        migrations.AddField(
            model_name='orden',
            name='lugar_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lugar_origen_orden', to='casetas.lugar'),
        ),
        migrations.AddField(
            model_name='orden',
            name='numero',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lugar',
            name='nombre',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='casetas.ruta'),
        ),
    ]
