# Generated by Django 4.2.13 on 2024-05-09 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casetas', '0003_lugar_nombre_id_orden_lugar_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseta',
            name='lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='casetas.lugar'),
        ),
    ]
