# Generated by Django 4.2.13 on 2024-05-09 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casetas', '0004_alter_caseta_lugar'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadTractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='ordencaseta',
            name='tag',
        ),
        migrations.AddField(
            model_name='orden',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='casetas.unidadtractor'),
        ),
        migrations.AddField(
            model_name='ordencaseta',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='casetas.unidadtractor'),
        ),
    ]
