# Generated by Django 4.2.13 on 2024-05-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casetas', '0005_unidadtractor_remove_ordencaseta_tag_orden_unidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadtractor',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unidadtractor',
            name='tag',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
