# Generated by Django 4.2.13 on 2024-05-09 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casetas', '0007_ordencaseta_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencaseta',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='casetas.orden'),
        ),
    ]
