# Generated by Django 4.2.13 on 2024-06-07 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casetas', '0009_alter_lugar_options_alter_orden_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdenCaseta',
            new_name='Cruce',
        ),
        migrations.RenameModel(
            old_name='UnidadTractor',
            new_name='Unidad',
        ),
    ]
