# Generated by Django 4.2.13 on 2024-06-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casetas', '0010_rename_ordencaseta_cruce_rename_unidadtractor_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruce',
            name='ext_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
